"""Generate pydantic models and TypeScript types from shared/schemas.

    python -m audible_contracts.codegen --py-out <dir> --ts-out <dir>

Used by `make types` (writes into the repo) and `make check-types` (writes to a temp dir and diffs).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from audible_contracts.paths import REPO_ROOT, SCHEMAS_DIR

JSON2TS = "json-schema-to-typescript"
HEADER_TS = "// Generated by `make types` from shared/schemas. Do not edit by hand.\n"
HEADER_PY = "# Generated by `make types` from shared/schemas. Do not edit by hand.\n"


def schema_files() -> list[Path]:
    return sorted(SCHEMAS_DIR.glob("*.schema.json"))


def stem(path: Path) -> str:
    """`fact_sheet.schema.json` -> `fact_sheet`."""
    return path.name.removesuffix(".schema.json")


def own_titles(path: Path) -> list[str]:
    """Every titled subschema defined in this file (root first), in file order."""
    titles: list[str] = []

    def walk(node: object) -> None:
        if isinstance(node, dict):
            title = node.get("title")
            if isinstance(title, str) and title not in titles:
                titles.append(title)
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(json.loads(path.read_text()))
    return titles


def union_members(path: Path, title: str) -> list[str]:
    """Titles of the local $defs that a oneOf/anyOf def named `title` unions over."""
    defs = json.loads(path.read_text())["$defs"]
    node = next(d for d in defs.values() if d.get("title") == title)
    refs = [r["$ref"].removeprefix("#/$defs/") for r in node.get("oneOf", node.get("anyOf", []))]
    return [defs[r]["title"] for r in refs]


def generate_py(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            [
                "datamodel-codegen",
                "--input",
                str(SCHEMAS_DIR),
                "--input-file-type",
                "jsonschema",
                "--output",
                tmp,
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.12",
                "--enum-field-as-literal",
                "all",
                "--use-title-as-name",
                "--use-schema-description",
                "--use-standard-collections",
                "--use-union-operator",
                "--collapse-root-models",
                "--field-constraints",
                "--disable-timestamp",
                "--formatters",
                "ruff-format",
                "--custom-file-header",
                HEADER_PY.rstrip("\n"),
            ],
            check=True,
        )
        for old in out.glob("*.py"):
            old.unlink()
        for f in sorted(Path(tmp).glob("*_schema.py")):
            shutil.copy(f, out / f.name)
    doc = '"""Pydantic models for every shared/schemas file (one module per schema)."""\n\n'
    lines = [HEADER_PY, doc]
    aliases: list[str] = []
    exported: list[str] = []
    for path in schema_files():
        source = (out / f"{stem(path)}_schema.py").read_text()
        titles = [t for t in own_titles(path) if t not in exported]
        exported += titles
        classes = [t for t in titles if f"class {t}(" in source]
        lines.append(f"from .{stem(path)}_schema import {', '.join(classes)}\n")
        # --collapse-root-models inlines oneOf wrappers; re-expose them as union aliases.
        for title in (t for t in titles if t not in classes):
            members = union_members(path, title)
            aliases.append(f"type {title} = {' | '.join(members)}\n")
    lines += ["\n", *aliases]
    lines.append("\n__all__ = [\n" + "".join(f'    "{t}",\n' for t in exported) + "]\n")
    (out / "__init__.py").write_text("".join(lines))


def json2ts_cmd() -> list[str]:
    """web/'s installed json2ts, else npx at the version web/package.json pins (output differs
    between major versions, so both paths must resolve the same release)."""
    web = REPO_ROOT / "web"
    local = web / "node_modules" / ".bin" / "json2ts"
    if local.exists():
        return [str(local)]
    package = json.loads((web / "package.json").read_text())
    version = {**package.get("dependencies", {}), **package.get("devDependencies", {})}[JSON2TS]
    return ["npx", "--yes", f"{JSON2TS}@{version}"]


def generate_ts(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("*.ts"):
        old.unlink()
    cmd = json2ts_cmd()
    index = [HEADER_TS]
    exported: list[str] = []
    for path in schema_files():
        target = out / f"{stem(path)}.ts"
        subprocess.run(
            [
                *cmd,
                "--input",
                str(path),
                "--output",
                str(target),
                "--cwd",
                str(SCHEMAS_DIR),
                "--maxItems=-1",
                "--no-additionalProperties",
            ],
            check=True,
        )
        titles = [t for t in own_titles(path) if t not in exported]
        exported += titles
        index.append(f"export type {{ {', '.join(titles)} }} from './{stem(path)}';\n")
    (out / "index.ts").write_text("".join(index))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate pydantic + TS types from shared/schemas."
    )
    parser.add_argument("--py-out", type=Path, required=True)
    parser.add_argument("--ts-out", type=Path, required=True)
    args = parser.parse_args(argv)
    generate_py(args.py_out)
    generate_ts(args.ts_out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
