# Generated by `make types` from shared/schemas. Do not edit by hand.
"""Pydantic models for every shared/schemas file (one module per schema)."""

from .chat_request_schema import ChatRequest, ChatContext, ChatMessage
from .coordinator_call_schema import CoordinatorCall, CallOption, AlternativeCall, RationaleItem
from .fact_sheet_schema import FactSheet, Fact, MatchupFactSheetContext, SituationFactSheetContext, TeamFactSheetContext, FactSheetDerived
from .game_plan_report_schema import GamePlanReport, SituationalCalls, ReportKey
from .manifest_schema import Manifest, ManifestFiles, ManifestFile
from .playcaller_sample_schema import PlaycallerSample
from .player_season_row_schema import PlayerSeasonRow
from .report_index_entry_schema import ReportIndexEntry
from .scenario_schema import Scenario
from .schedule_game_schema import ScheduleGame
from .situation_schema import Situation
from .team_schema import Team
from .team_season_row_schema import TeamSeasonRow
from .team_tendency_row_schema import TeamTendencyRow
from .team_week_row_schema import TeamWeekRow

type FactSheetContext = MatchupFactSheetContext | SituationFactSheetContext | TeamFactSheetContext

__all__ = [
    "ChatRequest",
    "ChatContext",
    "ChatMessage",
    "CoordinatorCall",
    "CallOption",
    "AlternativeCall",
    "RationaleItem",
    "FactSheet",
    "Fact",
    "FactSheetContext",
    "MatchupFactSheetContext",
    "SituationFactSheetContext",
    "TeamFactSheetContext",
    "FactSheetDerived",
    "GamePlanReport",
    "SituationalCalls",
    "ReportKey",
    "Manifest",
    "ManifestFiles",
    "ManifestFile",
    "PlaycallerSample",
    "PlayerSeasonRow",
    "ReportIndexEntry",
    "Scenario",
    "ScheduleGame",
    "Situation",
    "Team",
    "TeamSeasonRow",
    "TeamTendencyRow",
    "TeamWeekRow",
]
