# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field
from . import situation_schema


class ChatMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["user", "assistant"]
    content: str


class ChatContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    page: Literal["team", "matchup", "play-caller", "other"]
    team: str | None = Field(..., pattern="^[A-Z]{2,3}$")
    opponent: str | None = Field(..., pattern="^[A-Z]{2,3}$")
    game_id: str | None = Field(
        ..., pattern="^[0-9]{4}_[0-9]{2}_[A-Z]{2,3}_[A-Z]{2,3}$"
    )
    situation: situation_schema.Situation | None


class ChatRequest(BaseModel):
    """
    Chat drawer request. The client prepends a fact-sheet system message; output is free text.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    context: ChatContext = Field(..., title="ChatContext")
    messages: list[ChatMessage]
