# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel


class CallOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    play_family: (
        Literal[
            "inside_run",
            "outside_run",
            "qb_run",
            "screen",
            "quick_pass",
            "intermediate_pass",
            "deep_pass",
            "play_action",
            "sneak",
            "punt",
            "field_goal",
        ]
        | None
    )
    direction: Literal["left", "middle", "right"] | None
    concept: str = Field(..., min_length=1)
    front: Literal["even", "odd", "bear", "dime_sub"] | None
    coverage_shell: (
        Literal["cover0", "cover1", "cover2", "cover3", "cover4", "cover6", "two_man"]
        | None
    )
    pressure: Literal["none", "sim", "blitz"] | None


class AlternativeCall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    play_family: (
        Literal[
            "inside_run",
            "outside_run",
            "qb_run",
            "screen",
            "quick_pass",
            "intermediate_pass",
            "deep_pass",
            "play_action",
            "sneak",
            "punt",
            "field_goal",
        ]
        | None
    )
    direction: Literal["left", "middle", "right"] | None
    concept: str = Field(..., min_length=1)
    front: Literal["even", "odd", "bear", "dime_sub"] | None
    coverage_shell: (
        Literal["cover0", "cover1", "cover2", "cover3", "cover4", "cover6", "two_man"]
        | None
    )
    pressure: Literal["none", "sim", "blitz"] | None
    when: str = Field(..., min_length=1)


class StatId(RootModel[str]):
    root: str = Field(
        ...,
        description="{team}.{side}.{season}.{grouping}.{cell_key}.{metric}",
        pattern="^[A-Z]{2,3}\\.(off|def)\\.[0-9]{4}\\.(overall|down_dist|down_dist_zone|zone|score_time|down_dist_score_time)\\.[a-z0-9_-]+\\.[a-z_]+$",
    )


class RationaleItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str = Field(..., min_length=1)
    stat_ids: list[StatId] = Field(..., min_length=1)


class CoordinatorCall(BaseModel):
    """
    Structured OC/DC recommendation. OC: play_family set, front/coverage_shell/pressure null. DC: front/coverage_shell/pressure set, play_family null.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["OC", "DC"]
    primary: CallOption
    alternatives: list[AlternativeCall] = Field(..., max_length=2)
    rationale: list[RationaleItem] = Field(..., max_length=5, min_length=2)
    confidence: Literal["low", "medium", "high"]
    caveats: list[str]
