# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal
from . import situation_schema


class Fact(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="{team}.{side}.{season}.{grouping}.{cell_key}.{metric}",
        pattern="^[A-Z]{2,3}\\.(off|def)\\.[0-9]{4}\\.(overall|down_dist|down_dist_zone|zone|score_time|down_dist_score_time)\\.[a-z0-9_-]+\\.[a-z_]+$",
    )
    label: str
    value: float
    display: str
    unit: Literal["rate", "epa", "count", "yards"]
    n: int = Field(..., ge=0)
    low_sample: bool
    league_value: float | None
    league_display: str | None


class MatchupFactSheetContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["matchup"]
    game_id: str = Field(..., pattern="^[0-9]{4}_[0-9]{2}_[A-Z]{2,3}_[A-Z]{2,3}$")
    season: int = Field(..., ge=1999, le=2100)
    team: str = Field(..., pattern="^[A-Z]{2,3}$")
    opponent: str = Field(..., pattern="^[A-Z]{2,3}$")
    role: Literal["OC", "DC"]


class TeamFactSheetContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["team"]
    season: int = Field(..., ge=1999, le=2100)
    team: str = Field(..., pattern="^[A-Z]{2,3}$")


class FactSheetDerived(BaseModel):
    """
    Buckets derived from the Situation (situation context only).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    down: int = Field(..., ge=1, le=4)
    dist_bucket: Literal["short", "medium", "long", "very_long"]
    field_zone: Literal["backed_up", "own_territory", "opp_territory", "red_zone"]
    score_state: Literal["trail_9plus", "trail_1_8", "tied", "lead_1_8", "lead_9plus"]
    time_bucket: Literal["two_minute", "fourth_quarter", "normal"]


class SituationFactSheetContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["situation"]
    situation: situation_schema.Situation


class FactSheet(BaseModel):
    """
    Deterministic bundle of facts handed to the model. derived is null for matchup and team contexts. Selection/order rules: shared/factsheet/SPEC.md.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    fact_sheet_version: str = Field(..., pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    context: (
        MatchupFactSheetContext | SituationFactSheetContext | TeamFactSheetContext
    ) = Field(..., title="FactSheetContext")
    derived: FactSheetDerived | None
    facts: list[Fact] = Field(..., max_length=40)
