# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from . import coordinator_call_schema, fact_sheet_schema
from typing import Literal
from datetime import date


class StatId(RootModel[str]):
    root: str = Field(
        ...,
        description="{team}.{side}.{season}.{grouping}.{cell_key}.{metric}",
        pattern="^[A-Z]{2,3}\\.(off|def)\\.[0-9]{4}\\.(overall|down_dist|down_dist_zone|zone|score_time|down_dist_score_time)\\.[a-z0-9_-]+\\.[a-z_]+$",
    )


class ReportKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str = Field(..., min_length=1)
    detail: str = Field(..., min_length=1)
    stat_ids: list[StatId] = Field(..., min_length=1)


class SituationalCalls(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    early_down: coordinator_call_schema.CoordinatorCall
    third_short: coordinator_call_schema.CoordinatorCall
    third_long: coordinator_call_schema.CoordinatorCall
    red_zone: coordinator_call_schema.CoordinatorCall
    two_minute: coordinator_call_schema.CoordinatorCall


class GamePlanReport(BaseModel):
    """
    reports/{season}/{week}/{game_id}.{team}.{role}.json. Reports with validation_status 'failed' are never shown.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    report_version: str = Field(..., pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    game_id: str = Field(..., pattern="^[0-9]{4}_[0-9]{2}_[A-Z]{2,3}_[A-Z]{2,3}$")
    season: int = Field(..., ge=1999, le=2100)
    week: int = Field(..., ge=1, le=22)
    team: str = Field(..., pattern="^[A-Z]{2,3}$")
    opponent: str = Field(..., pattern="^[A-Z]{2,3}$")
    role: Literal["OC", "DC"]
    generated_at: AwareDatetime
    stats_as_of: date
    provider: Literal["ollama", "claude", "claude-dev", "fake", "cloud"]
    model: str
    validation_status: Literal["passed", "failed"]
    fact_sheet: fact_sheet_schema.FactSheet
    headline: str = Field(..., min_length=1)
    keys: list[ReportKey] = Field(..., max_length=5, min_length=3)
    situational_calls: SituationalCalls = Field(..., title="SituationalCalls")
