# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from datetime import date


class Season(RootModel[int]):
    root: int = Field(..., ge=1999, le=2100)


class OptionalFieldsBySeasonItem(RootModel[int]):
    root: int = Field(..., ge=1999, le=2100)


class OptionalFieldsBySeason(RootModel[list[OptionalFieldsBySeasonItem]]):
    root: list[OptionalFieldsBySeasonItem]


class ManifestFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    sha256: str = Field(..., pattern="^[0-9a-f]{64}$")
    bytes: int = Field(..., ge=0)
    rows: int = Field(..., ge=0)


class ManifestFiles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    team_season: ManifestFile
    team_week: ManifestFile
    team_tendencies: ManifestFile
    player_season: ManifestFile
    schedule: ManifestFile


class Manifest(BaseModel):
    """
    data/manifest.json: read first by the web app (BUILD_PLAN 5.1, CONTRACTS 4.1).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: str = Field(..., pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    generated_at: AwareDatetime
    stats_as_of: date
    current_season: int = Field(..., ge=1999, le=2100)
    current_week: int = Field(..., ge=1, le=22)
    seasons: list[Season] = Field(..., min_length=1)
    files: ManifestFiles = Field(..., title="ManifestFiles")
    optional_fields_by_season: dict[str, OptionalFieldsBySeason] = Field(
        ...,
        description="Optional (nullable) metric column -> seasons in which it is populated.",
    )
