# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal


class PlayerSeasonRow(BaseModel):
    """
    One row of data/player_season.parquet: one player, one season, one team. cpoe is in percentage points (nflverse convention).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    season: int = Field(..., ge=1999, le=2100)
    player_id: str
    player_name: str
    team: str = Field(..., pattern="^[A-Z]{2,3}$")
    position: Literal["QB", "RB", "WR", "TE"]
    games: int = Field(..., ge=0)
    pass_att: int | None = Field(..., ge=0)
    completions: int | None = Field(..., ge=0)
    pass_yds: int | None
    pass_td: int | None = Field(..., ge=0)
    interceptions: int | None = Field(..., ge=0)
    sacks: int | None = Field(..., ge=0)
    epa_per_dropback: float | None
    cpoe: float | None
    any_a: float | None
    rush_att: int | None = Field(..., ge=0)
    rush_yds: int | None
    rush_td: int | None = Field(..., ge=0)
    epa_per_rush: float | None
    rush_success_rate: float | None = Field(..., ge=0.0, le=1.0)
    targets: int | None = Field(..., ge=0)
    receptions: int | None = Field(..., ge=0)
    rec_yds: int | None
    rec_td: int | None = Field(..., ge=0)
    epa_per_target: float | None
    target_share: float | None = Field(..., ge=0.0, le=1.0)
    air_yards_share: float | None
    yac_per_rec: float | None
