# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict
from . import coordinator_call_schema, fact_sheet_schema, situation_schema


class PlaycallerSample(BaseModel):
    """
    One entry of reports/samples/playcaller.json (an array of 3-5); shown in Sample mode.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    situation: situation_schema.Situation
    fact_sheet: fact_sheet_schema.FactSheet
    call: coordinator_call_schema.CoordinatorCall
    generated_at: AwareDatetime
    model: str
