# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from typing import Literal
from datetime import date


class ReportIndexEntry(BaseModel):
    """
    One entry of reports/index.json (an array of these).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    season: int = Field(..., ge=1999, le=2100)
    week: int = Field(..., ge=1, le=22)
    game_id: str = Field(..., pattern="^[0-9]{4}_[0-9]{2}_[A-Z]{2,3}_[A-Z]{2,3}$")
    team: str = Field(..., pattern="^[A-Z]{2,3}$")
    opponent: str = Field(..., pattern="^[A-Z]{2,3}$")
    role: Literal["OC", "DC"]
    path: str = Field(
        ...,
        description="Relative to reports/, week unpadded.",
        pattern="^[0-9]{4}/[0-9]{1,2}/[0-9]{4}_[0-9]{2}_[A-Z]{2,3}_[A-Z]{2,3}\\.[A-Z]{2,3}\\.(OC|DC)\\.json$",
    )
    generated_at: AwareDatetime
    stats_as_of: date
    model: str
    validation_status: Literal["passed", "failed"]
