# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal
from . import situation_schema


class Scenario(BaseModel):
    """
    Eval scenario. OC scenarios score play_family (DC lists null); DC scenarios score front, coverage_shell and pressure (play-family lists null). A null list means not scored.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., pattern="^(oc|dc)-[0-9]{2}-[a-z0-9-]+$")
    situation: situation_schema.Situation
    data: Literal["fixtures"]
    acceptable_play_families: (
        list[
            Literal[
                "inside_run",
                "outside_run",
                "qb_run",
                "screen",
                "quick_pass",
                "intermediate_pass",
                "deep_pass",
                "play_action",
                "sneak",
                "punt",
                "field_goal",
            ]
        ]
        | None
    )
    unacceptable_play_families: (
        list[
            Literal[
                "inside_run",
                "outside_run",
                "qb_run",
                "screen",
                "quick_pass",
                "intermediate_pass",
                "deep_pass",
                "play_action",
                "sneak",
                "punt",
                "field_goal",
            ]
        ]
        | None
    )
    acceptable_pressures: list[Literal["none", "sim", "blitz"]] | None
    unacceptable_pressures: list[Literal["none", "sim", "blitz"]] | None
    acceptable_coverage_shells: (
        list[
            Literal[
                "cover0", "cover1", "cover2", "cover3", "cover4", "cover6", "two_man"
            ]
        ]
        | None
    )
    acceptable_fronts: list[Literal["even", "odd", "bear", "dime_sub"]] | None
    notes_for_human_rater: str
