# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal
from datetime import date


class ScheduleGame(BaseModel):
    """
    One game in data/schedule.json (an array of these). Scores are null for unplayed games.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    game_id: str = Field(..., pattern="^[0-9]{4}_[0-9]{2}_[A-Z]{2,3}_[A-Z]{2,3}$")
    season: int = Field(..., ge=1999, le=2100)
    week: int = Field(..., ge=1, le=22)
    game_type: Literal["REG", "WC", "DIV", "CON", "SB"]
    gameday: date
    gametime: str | None = Field(..., pattern="^[0-2][0-9]:[0-5][0-9]$")
    home_team: str = Field(..., pattern="^[A-Z]{2,3}$")
    away_team: str = Field(..., pattern="^[A-Z]{2,3}$")
    home_score: int | None = Field(..., ge=0)
    away_score: int | None = Field(..., ge=0)
    stadium: str | None
    spread_line: float | None
    total_line: float | None
