# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Situation(BaseModel):
    """
    Play-Caller game state. score_diff is from the offense's perspective; quarter 5 = OT. Cross-field rule (not expressible here, enforced by validators): distance <= yardline_100.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["OC", "DC"]
    offense: str = Field(..., pattern="^[A-Z]{2,3}$")
    defense: str = Field(..., pattern="^[A-Z]{2,3}$")
    season: int = Field(..., ge=1999, le=2100)
    down: int = Field(..., ge=1, le=4)
    distance: int = Field(..., ge=1, le=99)
    yardline_100: int = Field(..., ge=1, le=99)
    quarter: int = Field(..., ge=1, le=5)
    clock_seconds: int = Field(..., ge=0, le=900)
    score_diff: int = Field(..., ge=-99, le=99)
    timeouts_offense: int = Field(..., ge=0, le=3)
    timeouts_defense: int = Field(..., ge=0, le=3)
