# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal


class TeamTendencyRow(BaseModel):
    """
    One row of data/team_tendencies.parquet. A grouping fills only its own dimension columns; the others are null. Buckets are from the offense's perspective on every row. Every metric except plays/low_sample is null when its denominator is 0 (CONTEXT.md). For side=def, metrics describe what the defense allowed/did.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    season: int = Field(..., ge=1999, le=2100)
    team: str = Field(..., pattern="^[A-Z]{2,3}$")
    side: Literal["off", "def"]
    grouping: Literal[
        "overall",
        "down_dist",
        "down_dist_zone",
        "zone",
        "score_time",
        "down_dist_score_time",
    ]
    down: int | None = Field(..., ge=1, le=4)
    dist_bucket: Literal["short", "medium", "long", "very_long"] | None
    field_zone: (
        Literal["backed_up", "own_territory", "opp_territory", "red_zone"] | None
    )
    score_state: (
        Literal["trail_9plus", "trail_1_8", "tied", "lead_1_8", "lead_9plus"] | None
    )
    time_bucket: Literal["two_minute", "fourth_quarter", "normal"] | None
    cell_key: str = Field(..., pattern="^[a-z0-9_-]+$")
    plays: int = Field(..., ge=0)
    low_sample: bool
    pass_rate: float | None = Field(..., ge=0.0, le=1.0)
    proe: float | None = Field(..., ge=-1.0, le=1.0)
    epa_per_play: float | None
    success_rate: float | None = Field(..., ge=0.0, le=1.0)
    explosive_rate: float | None = Field(..., ge=0.0, le=1.0)
    pass_epa: float | None
    run_epa: float | None
    pass_success_rate: float | None = Field(..., ge=0.0, le=1.0)
    run_success_rate: float | None = Field(..., ge=0.0, le=1.0)
    avg_air_yards: float | None
    deep_pass_rate: float | None = Field(..., ge=0.0, le=1.0)
    screen_rate: float | None = Field(..., ge=0.0, le=1.0)
    play_action_rate: float | None = Field(..., ge=0.0, le=1.0)
    shotgun_rate: float | None = Field(..., ge=0.0, le=1.0)
    no_huddle_rate: float | None = Field(..., ge=0.0, le=1.0)
    run_left_rate: float | None = Field(..., ge=0.0, le=1.0)
    run_middle_rate: float | None = Field(..., ge=0.0, le=1.0)
    run_right_rate: float | None = Field(..., ge=0.0, le=1.0)
    pass_left_rate: float | None = Field(..., ge=0.0, le=1.0)
    pass_middle_rate: float | None = Field(..., ge=0.0, le=1.0)
    pass_right_rate: float | None = Field(..., ge=0.0, le=1.0)
    sack_rate: float | None = Field(..., ge=0.0, le=1.0)
    blitz_rate: float | None = Field(..., ge=0.0, le=1.0)
    pressure_rate: float | None = Field(..., ge=0.0, le=1.0)
    man_rate: float | None = Field(..., ge=0.0, le=1.0)
    zone_rate: float | None = Field(..., ge=0.0, le=1.0)
