# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, ConfigDict, Field
from typing import Literal


class Team(BaseModel):
    """
    One team in shared/teams.json (an array of these). Abbreviations are nflverse's.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    abbr: str = Field(..., pattern="^[A-Z]{2,3}$")
    name: str
    nickname: str
    conference: Literal["AFC", "NFC"]
    division: Literal[
        "AFC East",
        "AFC North",
        "AFC South",
        "AFC West",
        "NFC East",
        "NFC North",
        "NFC South",
        "NFC West",
    ]
    color_primary: str = Field(..., pattern="^#[0-9A-Fa-f]{6}$")
    color_secondary: str = Field(..., pattern="^#[0-9A-Fa-f]{6}$")
    logo: str | None
    logo_url: AnyUrl | None = Field(
        ...,
        description="Team logo (nflverse team_logo_espn), hotlinked; never committed as a file.",
    )
    wordmark_url: AnyUrl | None = Field(
        ..., description="Team wordmark (nflverse team_wordmark), hotlinked."
    )
