# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class TeamSeasonRow(BaseModel):
    """
    One row of data/team_season.parquet: one team (or NFL) in one season. rank_<metric>: 1 = best per CONTEXT.md rank direction, min-rank ties, null for NFL rows and null metrics.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    season: int = Field(..., ge=1999, le=2100)
    team: str = Field(..., pattern="^[A-Z]{2,3}$")
    games: int = Field(..., ge=0)
    off_plays: int = Field(..., ge=0)
    off_epa_per_play: float | None
    off_pass_epa: float | None
    off_run_epa: float | None
    off_success_rate: float | None = Field(..., ge=0.0, le=1.0)
    off_explosive_rate: float | None = Field(..., ge=0.0, le=1.0)
    off_pass_rate: float | None = Field(..., ge=0.0, le=1.0)
    off_proe: float | None = Field(..., ge=-1.0, le=1.0)
    off_early_down_pass_rate: float | None = Field(..., ge=0.0, le=1.0)
    off_third_down_conv_rate: float | None = Field(..., ge=0.0, le=1.0)
    off_red_zone_td_rate: float | None = Field(..., ge=0.0, le=1.0)
    def_plays: int = Field(..., ge=0)
    def_epa_per_play: float | None
    def_pass_epa: float | None
    def_run_epa: float | None
    def_success_rate: float | None = Field(..., ge=0.0, le=1.0)
    def_explosive_rate: float | None = Field(..., ge=0.0, le=1.0)
    def_third_down_conv_rate: float | None = Field(..., ge=0.0, le=1.0)
    def_red_zone_td_rate: float | None = Field(..., ge=0.0, le=1.0)
    def_blitz_rate: float | None = Field(..., ge=0.0, le=1.0)
    def_pressure_rate: float | None = Field(..., ge=0.0, le=1.0)
    rank_off_epa_per_play: int | None = Field(..., ge=1, le=32)
    rank_off_pass_epa: int | None = Field(..., ge=1, le=32)
    rank_off_run_epa: int | None = Field(..., ge=1, le=32)
    rank_off_success_rate: int | None = Field(..., ge=1, le=32)
    rank_off_explosive_rate: int | None = Field(..., ge=1, le=32)
    rank_off_pass_rate: int | None = Field(..., ge=1, le=32)
    rank_off_proe: int | None = Field(..., ge=1, le=32)
    rank_off_early_down_pass_rate: int | None = Field(..., ge=1, le=32)
    rank_off_third_down_conv_rate: int | None = Field(..., ge=1, le=32)
    rank_off_red_zone_td_rate: int | None = Field(..., ge=1, le=32)
    rank_def_epa_per_play: int | None = Field(..., ge=1, le=32)
    rank_def_pass_epa: int | None = Field(..., ge=1, le=32)
    rank_def_run_epa: int | None = Field(..., ge=1, le=32)
    rank_def_success_rate: int | None = Field(..., ge=1, le=32)
    rank_def_explosive_rate: int | None = Field(..., ge=1, le=32)
    rank_def_third_down_conv_rate: int | None = Field(..., ge=1, le=32)
    rank_def_red_zone_td_rate: int | None = Field(..., ge=1, le=32)
    rank_def_blitz_rate: int | None = Field(..., ge=1, le=32)
    rank_def_pressure_rate: int | None = Field(..., ge=1, le=32)
