# Generated by `make types` from shared/schemas. Do not edit by hand.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class TeamWeekRow(BaseModel):
    """
    One row of data/team_week.parquet: one team in one played game.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    season: int = Field(..., ge=1999, le=2100)
    week: int = Field(..., ge=1, le=22)
    game_id: str = Field(..., pattern="^[0-9]{4}_[0-9]{2}_[A-Z]{2,3}_[A-Z]{2,3}$")
    team: str = Field(..., pattern="^[A-Z]{2,3}$")
    opponent: str = Field(..., pattern="^[A-Z]{2,3}$")
    is_home: bool
    points_for: int = Field(..., ge=0)
    points_against: int = Field(..., ge=0)
    off_plays: int = Field(..., ge=0)
    off_epa_per_play: float | None
    off_success_rate: float | None = Field(..., ge=0.0, le=1.0)
    off_pass_rate: float | None = Field(..., ge=0.0, le=1.0)
    off_proe: float | None = Field(..., ge=-1.0, le=1.0)
    def_plays: int = Field(..., ge=0)
    def_epa_per_play: float | None
    def_success_rate: float | None = Field(..., ge=0.0, le=1.0)
